package com.qiuqiu.pet;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.net.Uri;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;import java.util.concurrent.*;

public class AlbumDetailActivity extends Activity {
 static final int PICK=61;final ExecutorService io=Executors.newSingleThreadExecutor();final Handler timer=new Handler(Looper.getMainLooper());String albumId,albumName;LinearLayout gallery;TextView status;
 int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
 TextView text(String s,int z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(0xff594747);t.setPadding(dp(4),dp(8),dp(4),dp(8));return t;}
 @Override public void onCreate(Bundle b){super.onCreate(b);albumId=getIntent().getStringExtra("albumId");albumName=getIntent().getStringExtra("albumName");LinearLayout page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setBackgroundColor(0xfffffbf5);LinearLayout top=new LinearLayout(this);top.setPadding(dp(12),dp(12),dp(12),dp(8));top.setGravity(Gravity.CENTER_VERTICAL);page.addView(top);TextView h=text(albumName,23);top.addView(h,new LinearLayout.LayoutParams(0,-2,1));Button add=new Button(this);add.setText("📷 添加照片");add.setOnClickListener(v->pick());top.addView(add,new LinearLayout.LayoutParams(dp(125),dp(52)));status=text("",13);page.addView(status);ScrollView scroll=new ScrollView(this);gallery=new LinearLayout(this);gallery.setOrientation(LinearLayout.VERTICAL);gallery.setPadding(dp(12),dp(5),dp(12),dp(25));scroll.addView(gallery);page.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(page);load();}
 void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE);i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);startActivityForResult(i,PICK);}
 @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(req!=PICK||result!=RESULT_OK||data==null)return;List<Uri> uris=new ArrayList<>();if(data.getClipData()!=null)for(int i=0;i<data.getClipData().getItemCount();i++)uris.add(data.getClipData().getItemAt(i).getUri());else if(data.getData()!=null)uris.add(data.getData());status.setText("正在保存 "+uris.size()+" 张照片……");io.execute(()->{int ok=0;for(Uri uri:uris)try{String body=AlbumImages.encode(this,uri);SharedFeatureStore.save(this,"_album_photo:"+albumId,"照片",body,"shared");ok++;}catch(Exception ignored){}int saved=ok;runOnUiThread(()->{status.setText("已添加 "+saved+" 张，联网后自动同步");new Handler().postDelayed(this::load,400);});});}
 void load(){io.execute(()->{List<SharedItem> list=SyncDatabase.get(this).shared().byCategory("_album_photo:"+albumId);runOnUiThread(()->render(list));});}
 void render(List<SharedItem> list){gallery.removeAllViews();if(list.isEmpty()){gallery.addView(text("相册还是空的，点击“添加照片”把共同回忆放进来。",15));return;}String previous="";GridLayout grid=null;SimpleDateFormat fmt=new SimpleDateFormat("yyyy年M月d日",Locale.CHINA);for(SharedItem item:list){String day=fmt.format(new Date(item.createdAt));if(!day.equals(previous)){gallery.addView(text(day,17));grid=new GridLayout(this);grid.setColumnCount(3);gallery.addView(grid,new LinearLayout.LayoutParams(-1,-2));previous=day;}Bitmap bitmap=AlbumImages.decode(item.body,360);if(bitmap==null)continue;ImageView image=new ImageView(this);image.setImageBitmap(bitmap);image.setScaleType(ImageView.ScaleType.CENTER_CROP);image.setContentDescription("打开照片");image.setOnClickListener(v->startActivity(new Intent(this,PhotoViewerActivity.class).putExtra("itemId",item.id)));image.setOnLongClickListener(v->{new AlertDialog.Builder(this).setMessage("删除这张照片？").setNegativeButton("取消",null).setPositiveButton("删除",(d,w)->{SharedFeatureStore.update(this,item,true);new Handler().postDelayed(this::load,300);}).show();return true;});GridLayout.LayoutParams lp=new GridLayout.LayoutParams();lp.width=0;lp.height=dp(115);lp.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1,1f);lp.setMargins(dp(3),dp(3),dp(3),dp(3));grid.addView(image,lp);}}
 final Runnable live=new Runnable(){public void run(){load();timer.postDelayed(this,3500);}};
 @Override protected void onResume(){super.onResume();RealtimeSyncService.start(this);new SyncRepository(this).syncAsync((ok,msg)->load());timer.post(live);}
 @Override protected void onPause(){timer.removeCallbacks(live);super.onPause();}
 @Override protected void onDestroy(){timer.removeCallbacksAndMessages(null);io.shutdownNow();super.onDestroy();}
}
