package com.qiuqiu.pet;
import android.content.*;import android.graphics.*;import android.net.Uri;import android.provider.MediaStore;import android.util.Base64;import java.io.*;
final class AlbumImages {
 static final String MARK="[[qiuqiu-image:xx";
 static String encode(Context c,Uri uri)throws Exception{BitmapFactory.Options bounds=new BitmapFactory.Options();bounds.inJustDecodeBounds=true;try(InputStream in=c.getContentResolver().openInputStream(uri)){if(in==null)throw new IOException("无法读取照片");BitmapFactory.decodeStream(in,null,bounds);}int sample=1;while(Math.max(bounds.outWidth,bounds.outHeight)/sample>1600)sample*=2;BitmapFactory.Options options=new BitmapFactory.Options();options.inSampleSize=sample;options.inPreferredConfig=Bitmap.Config.RGB_565;Bitmap src;try(InputStream in=c.getContentResolver().openInputStream(uri)){if(in==null)throw new IOException("无法读取照片");src=BitmapFactory.decodeStream(in,null,options);}if(src==null)throw new IOException("照片格式无法读取");Bitmap out=src;try{int max=Math.max(src.getWidth(),src.getHeight());float scale=max>1280?1280f/max:1f;if(scale<1)out=Bitmap.createScaledBitmap(src,Math.round(src.getWidth()*scale),Math.round(src.getHeight()*scale),true);for(int q=82;q>=42;q-=8){ByteArrayOutputStream b=new ByteArrayOutputStream();out.compress(Bitmap.CompressFormat.JPEG,q,b);if(b.size()<600000||q==42)return MARK+Base64.encodeToString(b.toByteArray(),Base64.NO_WRAP)+"]]";}throw new IOException("照片压缩失败");}finally{if(out!=src)out.recycle();src.recycle();}}
 static byte[] bytes(String body){try{int a=body.indexOf(MARK),e=body.indexOf("]]",a);if(a<0||e<0)return null;return Base64.decode(body.substring(a+MARK.length(),e),Base64.DEFAULT);}catch(Exception e){return null;}}
 static Bitmap decode(String body){return decode(body,0);}
 static Bitmap decode(String body,int maxDimension){byte[] b=bytes(body);if(b==null)return null;BitmapFactory.Options bounds=new BitmapFactory.Options();bounds.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(b,0,b.length,bounds);BitmapFactory.Options options=new BitmapFactory.Options();if(maxDimension>0){int sample=1;while(Math.max(bounds.outWidth,bounds.outHeight)/sample>maxDimension)sample*=2;options.inSampleSize=sample;options.inPreferredConfig=Bitmap.Config.RGB_565;}return BitmapFactory.decodeByteArray(b,0,b.length,options);}
 private AlbumImages(){}
}
