package com.qiuqiu.pet;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Typeface;import android.view.*;import android.widget.*;import java.util.*;import java.util.concurrent.*;

public class AlbumListActivity extends Activity {
 static final int[] COVERS={R.drawable.album_cover_spring,R.drawable.album_cover_night,R.drawable.album_cover_birthday};static final String[] KEYS={"spring","night","birthday"};
 final ExecutorService io=Executors.newSingleThreadExecutor();final Handler timer=new Handler(Looper.getMainLooper());LinearLayout root,cards;TextView count;
 int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
 @Override public void onCreate(Bundle b){super.onCreate(b);ScrollView page=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(18),dp(16),dp(28));root.setBackgroundColor(0xfffffbf5);page.addView(root);LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);root.addView(top);TextView title=text("🐾 球球相册",25);title.setTypeface(Typeface.DEFAULT_BOLD);top.addView(title,new LinearLayout.LayoutParams(0,-2,1));Button create=new Button(this);create.setText("＋ 新建");create.setOnClickListener(v->createDialog());top.addView(create,new LinearLayout.LayoutParams(dp(100),dp(50)));root.addView(text("左右滑动浏览拍立得相册。相册数量不限，双方添加的照片会自动同步。",14));HorizontalScrollView hs=new HorizontalScrollView(this);cards=new LinearLayout(this);cards.setGravity(Gravity.CENTER_VERTICAL);cards.setPadding(dp(3),dp(14),dp(3),dp(14));hs.addView(cards);root.addView(hs,new LinearLayout.LayoutParams(-1,dp(460)));count=text("",15);root.addView(count);setContentView(page);}
 TextView text(String s,int z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(0xff584848);t.setPadding(dp(3),dp(7),dp(3),dp(7));return t;}
 final Runnable live=new Runnable(){public void run(){new SyncRepository(AlbumListActivity.this).syncAsync((ok,msg)->{if(!ok)count.setText(msg);load();});timer.postDelayed(this,5000);}};
 @Override protected void onResume(){super.onResume();RealtimeSyncService.start(this);new SyncRepository(this).syncAsync((ok,msg)->load());timer.post(live);}
 @Override protected void onPause(){timer.removeCallbacks(live);super.onPause();}
 void load(){io.execute(()->{List<SharedItem> albums=SyncDatabase.get(this).shared().byCategory("_album");List<SharedItem> photos=SyncDatabase.get(this).shared().byPrefix("_album_photo:%");runOnUiThread(()->render(albums,photos));});}
 void render(List<SharedItem> albums,List<SharedItem> photos){cards.removeAllViews();int total=photos.size();count.setText("照片数量："+total+"   ·   相册数量不限");if(albums.isEmpty()){cards.addView(text("还没有相册，点击右上角“新建”选择球球封面。",16),new LinearLayout.LayoutParams(dp(300),-2));return;}for(SharedItem album:albums){int photoCount=0;for(SharedItem p:photos)if(p.category.equals("_album_photo:"+album.id))photoCount++;LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(12),dp(12),dp(12),dp(8));card.setBackgroundColor(0xffffffff);ImageView cover=new ImageView(this);cover.setImageResource(coverRes(album.body));cover.setScaleType(ImageView.ScaleType.CENTER_CROP);card.addView(cover,new LinearLayout.LayoutParams(dp(250),dp(280)));card.addView(text(album.title,19));LinearLayout foot=new LinearLayout(this);TextView n=text(photoCount+" 张",13);foot.addView(n,new LinearLayout.LayoutParams(0,-2,1));Button more=new Button(this);more.setText("⋮");more.setOnClickListener(v->menu(album));foot.addView(more,new LinearLayout.LayoutParams(dp(54),dp(46)));card.addView(foot);card.setOnClickListener(v->startActivity(new Intent(this,AlbumDetailActivity.class).putExtra("albumId",album.id).putExtra("albumName",album.title)));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(dp(280),dp(420));lp.setMargins(dp(8),0,dp(8),0);cards.addView(card,lp);}}
 static int coverRes(String body){if(body.contains("night"))return COVERS[1];if(body.contains("birthday"))return COVERS[2];return COVERS[0];}
 void createDialog(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(12),0,dp(12),0);EditText name=new EditText(this);name.setHint("相册名称");box.addView(name);TextView label=text("选择球球封面",16);box.addView(label);LinearLayout choices=new LinearLayout(this);box.addView(choices);int[] selected={0};for(int i=0;i<COVERS.length;i++){final int index=i;ImageView image=new ImageView(this);image.setImageResource(COVERS[i]);image.setScaleType(ImageView.ScaleType.CENTER_CROP);image.setAlpha(i==0?1f:.45f);image.setOnClickListener(v->{selected[0]=index;for(int j=0;j<choices.getChildCount();j++)choices.getChildAt(j).setAlpha(j==index?1f:.45f);});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(105),1);lp.setMargins(dp(3),dp(3),dp(3),dp(3));choices.addView(image,lp);}new AlertDialog.Builder(this).setTitle("新建相册").setView(box).setNegativeButton("取消",null).setPositiveButton("创建",(d,w)->{String n=name.getText().toString().trim();if(n.isEmpty())n="球球回忆";SharedFeatureStore.save(this,"_album",n,"cover="+KEYS[selected[0]],"shared");new Handler().postDelayed(this::load,300);}).show();}
 void menu(SharedItem album){String[] ops={"重命名","更换封面","删除相册"};new AlertDialog.Builder(this).setTitle(album.title).setItems(ops,(d,which)->{if(which==0)rename(album);else if(which==1)changeCover(album);else new AlertDialog.Builder(this).setMessage("删除相册？相册中的照片也将不再显示。").setNegativeButton("取消",null).setPositiveButton("删除",(x,y)->{SharedFeatureStore.update(this,album,true);new Handler().postDelayed(this::load,300);}).show();}).show();}
 void rename(SharedItem album){EditText e=new EditText(this);e.setText(album.title);new AlertDialog.Builder(this).setTitle("重命名").setView(e).setNegativeButton("取消",null).setPositiveButton("保存",(d,w)->{album.title=e.getText().toString().trim();SharedFeatureStore.update(this,album,false);new Handler().postDelayed(this::load,300);}).show();}
 void changeCover(SharedItem album){String[] names={"🌸 春日球球","🌙 月夜球球","🎂 生日球球"};new AlertDialog.Builder(this).setTitle("选择封面").setItems(names,(d,w)->{album.body="cover="+KEYS[w];SharedFeatureStore.update(this,album,false);new Handler().postDelayed(this::load,300);}).show();}
 @Override protected void onDestroy(){timer.removeCallbacksAndMessages(null);io.shutdownNow();super.onDestroy();}
}
