package com.qiuqiu.pet;

import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.Typeface;import android.content.*;import android.database.Cursor;import android.net.Uri;import android.provider.OpenableColumns;import android.view.*;import android.widget.*;import android.graphics.drawable.GradientDrawable;import java.io.*;import java.text.*;import java.util.*;import java.util.concurrent.*;

public class ChatActivity extends Activity {
 static final int PICK_MEDIA=74;final ExecutorService io=Executors.newSingleThreadExecutor();final Handler timer=new Handler(Looper.getMainLooper());final Set<String> downloading=Collections.synchronizedSet(new HashSet<>());ServerConfig cfg;SyncRepository sync;LinearLayout messages;ScrollView scroll;EditText draft;Button sendButton;
 static final String[] STICKER_CAPTIONS={"贴贴","爱你","开心","委屈","生气","困困","想你","加油","谢谢","抱抱","撒娇","震惊","收到","晚安","冲呀","摸摸","开饭啦","哭哭","转圈","比心"};
 static final String[] STICKER_POSES={"lie","happy","happy","lie","disgust","sit","happy","run","sit","happy","treat","disgust","sit","lie","run","groom","kibble","lie","run","happy"};
 static final String[] STICKER_MARKS={"💕","💗","😸","🥺","😾","💤","🐾","💪","🙏","🫂","😽","😲","👌","🌙","✨","🫳","🍚","😭","🌀","🫶"};
 int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
 @Override public void onCreate(Bundle b){super.onCreate(b);cfg=new ServerConfig(this);sync=new SyncRepository(this);LinearLayout page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setBackgroundColor(0xfffff8f3);LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER);top.setPadding(dp(10),dp(8),dp(10),dp(6));TextView title=new TextView(this);title.setText("💬 我和另一位主人");title.setTextSize(20);title.setTypeface(Typeface.DEFAULT_BOLD);title.setTextColor(0xff594747);title.setGravity(Gravity.CENTER);top.addView(title,new LinearLayout.LayoutParams(0,-2,1));Button voiceCall=new Button(this);voiceCall.setText("☎");voiceCall.setOnClickListener(v->callUnavailable(false));top.addView(voiceCall,new LinearLayout.LayoutParams(dp(48),dp(44)));Button videoCall=new Button(this);videoCall.setText("▣");videoCall.setOnClickListener(v->callUnavailable(true));top.addView(videoCall,new LinearLayout.LayoutParams(dp(48),dp(44)));page.addView(top);scroll=new ScrollView(this);messages=new LinearLayout(this);messages.setOrientation(LinearLayout.VERTICAL);messages.setPadding(dp(12),dp(8),dp(12),dp(8));scroll.addView(messages);page.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));LinearLayout composer=new LinearLayout(this);composer.setGravity(Gravity.CENTER_VERTICAL);composer.setPadding(dp(5),dp(5),dp(5),dp(8));Button more=new Button(this);more.setText("＋");more.setTextSize(21);more.setOnClickListener(v->chooseMedia());composer.addView(more,new LinearLayout.LayoutParams(dp(48),dp(50)));Button stickers=new Button(this);stickers.setText("😊");stickers.setOnClickListener(v->showStickers());composer.addView(stickers,new LinearLayout.LayoutParams(dp(48),dp(50)));draft=new EditText(this);draft.setHint("说点什么……");draft.setMaxLines(4);composer.addView(draft,new LinearLayout.LayoutParams(0,-2,1));sendButton=new Button(this);sendButton.setText("发送");sendButton.setOnClickListener(v->send());composer.addView(sendButton,new LinearLayout.LayoutParams(dp(72),dp(50)));page.addView(composer);setContentView(page);load();}
 void callUnavailable(boolean video){new AlertDialog.Builder(this).setTitle(video?"视频通话":"语音通话").setMessage("当前共养服务器只支持消息同步，还没有实时通话信令和媒体中继，因此暂时无法接通。需要部署公网 WebRTC/TURN 服务后才能启用真实通话。图片、视频和球球动态表情可以正常发送。 ").setPositiveButton("知道了",null).show();}
 void send(){String s=draft.getText().toString().trim();if(s.isEmpty())return;if(!cfg.configured()){Toast.makeText(this,"请先登录账户并创建或加入球球",Toast.LENGTH_LONG).show();return;}SharedFeatureStore.save(this,"_chat",cfg.displayName(),s,"shared");draft.setText("");timer.postDelayed(this::load,250);}
 void chooseMedia(){String[] choices={"发送图片","发送视频","发送音频文件"};new AlertDialog.Builder(this).setTitle("发送附件").setItems(choices,(d,w)->{String type=w==0?"image/*":w==1?"video/*":"audio/*";Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType(type).addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PICK_MEDIA);}).show();}
 @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(req!=PICK_MEDIA||result!=RESULT_OK||data==null||data.getData()==null)return;Uri uri=data.getData();String mime=getContentResolver().getType(uri);if(mime==null||!(mime.startsWith("image/")||mime.startsWith("video/")||mime.startsWith("audio/"))){Toast.makeText(this,"请选择图片、视频或音频文件",Toast.LENGTH_LONG).show();return;}if(!cfg.configured()){Toast.makeText(this,"请先连接共养账户",Toast.LENGTH_LONG).show();return;}String name=fileName(uri);sendButton.setEnabled(false);Toast.makeText(this,"正在上传附件……",Toast.LENGTH_SHORT).show();io.execute(()->{try{byte[] bytes=readUri(uri,10*1024*1024);String id=sync.uploadChatMedia(bytes,mime);String body=ChatMedia.body(id,mime,name,bytes.length);SharedFeatureStore.save(this,"_chat",cfg.displayName(),body,"shared");runOnUiThread(()->{sendButton.setEnabled(true);Toast.makeText(this,"已发送",Toast.LENGTH_SHORT).show();load();});}catch(Exception e){runOnUiThread(()->{sendButton.setEnabled(true);Toast.makeText(this,"附件发送失败："+e.getMessage(),Toast.LENGTH_LONG).show();});}});}
 byte[] readUri(Uri uri,int limit)throws Exception{try(InputStream in=getContentResolver().openInputStream(uri);ByteArrayOutputStream out=new ByteArrayOutputStream()){if(in==null)throw new IOException("无法读取文件");byte[] b=new byte[16384];int n;while((n=in.read(b))!=-1){if(out.size()+n>limit)throw new IOException("附件超过 10 MB，请选择较短的视频");out.write(b,0,n);}return out.toByteArray();}}
 String fileName(Uri uri){try(Cursor c=getContentResolver().query(uri,null,null,null,null)){if(c!=null&&c.moveToFirst()){int i=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(i>=0)return c.getString(i);}}catch(Exception ignored){}return "球球聊天附件";}
 void load(){io.execute(()->{SyncDatabase db=SyncDatabase.get(this);List<SharedItem> list=db.shared().byCategory("_chat");ChatReadReceipts.markLatestIncoming(this,list,cfg.actorId(),cfg.displayName());long otherRead=ChatReadReceipts.readAt(db.shared().byCategory(ChatReadReceipts.CATEGORY),cfg.actorId());Collections.reverse(list);runOnUiThread(()->render(list,otherRead));});}
 void render(List<SharedItem> list,long otherRead){messages.removeAllViews();if(list.isEmpty()){TextView empty=bubble("还没有消息，先和对方打个招呼吧 🐾",false);messages.addView(empty);}for(SharedItem x:list){boolean mine=x.createdBy.equals(cfg.actorId());LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);row.setGravity(mine?Gravity.END:Gravity.START);LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(12),dp(8),dp(12),dp(8));card.setBackground(bg(mine?0xffffdfe7:0xffffffff,16));TextView who=bubble((mine?"我":x.title)+"  "+new SimpleDateFormat("MM-dd HH:mm",Locale.CHINA).format(new Date(x.createdAt)),false);who.setTextSize(11);card.addView(who);ChatMedia.Item media=ChatMedia.parse(x.body);if(media!=null)card.addView(mediaBubble(media));else if(x.body.startsWith("[[qiuqiu-sticker:")){int index=stickerIndex(x.body);if(index>=0)card.addView(animatedSticker(index));else card.addView(bubble("球球表情",mine));}else card.addView(bubble(x.body,mine));row.addView(card,new LinearLayout.LayoutParams(-2,-2));if(mine&&otherRead>=x.createdAt){TextView read=bubble("已读",false);read.setTextSize(11);read.setTextColor(0xffaaa4a0);read.setGravity(Gravity.RIGHT);row.addView(read);}LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(4),0,dp(4));messages.addView(row,lp);}scroll.post(()->scroll.fullScroll(View.FOCUS_DOWN));}
 Bitmap decodePreview(File file){try{BitmapFactory.Options bounds=new BitmapFactory.Options();bounds.inJustDecodeBounds=true;BitmapFactory.decodeFile(file.getAbsolutePath(),bounds);BitmapFactory.Options opts=new BitmapFactory.Options();opts.inSampleSize=sampleSize(bounds.outWidth,bounds.outHeight,dp(128));opts.inPreferredConfig=Bitmap.Config.RGB_565;return BitmapFactory.decodeFile(file.getAbsolutePath(),opts);}catch(OutOfMemoryError|RuntimeException ignored){return null;}}
 Bitmap decodePreview(byte[] bytes){try{BitmapFactory.Options bounds=new BitmapFactory.Options();bounds.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(bytes,0,bytes.length,bounds);BitmapFactory.Options opts=new BitmapFactory.Options();opts.inSampleSize=sampleSize(bounds.outWidth,bounds.outHeight,dp(128));opts.inPreferredConfig=Bitmap.Config.RGB_565;return BitmapFactory.decodeByteArray(bytes,0,bytes.length,opts);}catch(OutOfMemoryError|RuntimeException ignored){return null;}}
 int sampleSize(int width,int height,int maxSide){int sample=1;while(width/sample>maxSide||height/sample>maxSide)sample*=2;return sample;}
 View mediaBubble(ChatMedia.Item media){LinearLayout box=new LinearLayout(this);box.setGravity(Gravity.CENTER_VERTICAL);box.setPadding(dp(5),dp(5),dp(10),dp(5));box.setBackground(bg(0x14a05e64,12));ImageView icon=new ImageView(this);int size=dp(64);icon.setLayoutParams(new LinearLayout.LayoutParams(size,size));File cached=mediaFile(media);if(media.mime.startsWith("image/")&&cached.isFile()){Bitmap b=decodePreview(cached);if(b!=null){icon.setImageBitmap(b);icon.setScaleType(ImageView.ScaleType.CENTER_CROP);}}else icon.setImageResource(media.mime.startsWith("video/")?android.R.drawable.ic_media_play:android.R.drawable.ic_btn_speak_now);box.addView(icon);TextView label=bubble(media.name+"\n"+media.size/1024+" KB",false);label.setPadding(dp(8),0,0,0);box.addView(label);box.setOnClickListener(v->openMedia(media));if(media.mime.startsWith("image/")&&!cached.isFile())downloadThumbnail(media,icon);return box;}
 void downloadThumbnail(ChatMedia.Item m,ImageView target){String key="thumb:"+m.id;if(!downloading.add(key))return;io.execute(()->{try{byte[] bytes=sync.downloadChatMedia(m.id);File f=mediaFile(m);f.getParentFile().mkdirs();try(FileOutputStream out=new FileOutputStream(f)){out.write(bytes);}Bitmap b=decodePreview(bytes);runOnUiThread(()->{if(b!=null){target.setImageBitmap(b);target.setScaleType(ImageView.ScaleType.CENTER_CROP);}});}catch(Exception ignored){}finally{downloading.remove(key);}});}
 void openMedia(ChatMedia.Item m){File cached=mediaFile(m);if(cached.isFile()){launchMedia(cached,m);return;}if(!downloading.add(m.id)){Toast.makeText(this,"正在下载附件",Toast.LENGTH_SHORT).show();return;}Toast.makeText(this,"正在下载附件……",Toast.LENGTH_SHORT).show();io.execute(()->{try{byte[] bytes=sync.downloadChatMedia(m.id);File f=mediaFile(m);f.getParentFile().mkdirs();try(FileOutputStream out=new FileOutputStream(f)){out.write(bytes);}runOnUiThread(()->launchMedia(f,m));}catch(Exception e){runOnUiThread(()->Toast.makeText(this,"附件下载失败："+e.getMessage(),Toast.LENGTH_LONG).show());}finally{downloading.remove(m.id);}});}
 File mediaFile(ChatMedia.Item m){String ext=m.mime.startsWith("image/")?".jpg":m.mime.startsWith("video/")?".mp4":".m4a";return new File(getExternalFilesDir(null),m.id+ext);}
 void launchMedia(File f,ChatMedia.Item m){try{Uri uri=new Uri.Builder().scheme("content").authority(getPackageName()+".provider").appendPath(f.getName()).build();Intent i=new Intent(Intent.ACTION_VIEW).setDataAndType(uri,m.mime).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(i);}catch(Exception e){Toast.makeText(this,"没有可打开此附件的应用",Toast.LENGTH_LONG).show();}}
 int stickerIndex(String body){try{return Integer.parseInt(body.substring(body.indexOf(':')+1,body.indexOf("]]")));}catch(Exception e){return -1;}}
 View animatedSticker(int index){LinearLayout sticker=new LinearLayout(this);sticker.setGravity(Gravity.CENTER);sticker.setOrientation(LinearLayout.VERTICAL);CatView cat=new CatView(this);cat.mode=STICKER_POSES[index];cat.food=cat.mode.equals("eat")?"猫粮":"";cat.idleStartedUptime=SystemClock.uptimeMillis();cat.setLayoutParams(new LinearLayout.LayoutParams(dp(112),dp(104)));sticker.addView(cat);TextView caption=bubble(STICKER_MARKS[index]+" "+STICKER_CAPTIONS[index],false);caption.setGravity(Gravity.CENTER);caption.setTextColor(0xffaa6d7b);caption.setTextSize(12);sticker.addView(caption);return sticker;}
 void showStickers(){ScrollView sc=new ScrollView(this);GridLayout grid=new GridLayout(this);grid.setColumnCount(4);sc.addView(grid);for(int n=0;n<STICKER_CAPTIONS.length;n++){final int index=n;Button b=new Button(this);b.setAllCaps(false);b.setText(STICKER_MARKS[n]+"\n"+STICKER_CAPTIONS[n]);GridLayout.LayoutParams lp=new GridLayout.LayoutParams();lp.width=dp(82);lp.height=dp(72);grid.addView(b,lp);b.setOnClickListener(v->{new AlertDialog.Builder(this).setTitle("发送球球表情").setMessage(STICKER_MARKS[index]+"  "+STICKER_CAPTIONS[index]).setNegativeButton("取消",null).setPositiveButton("发送",(d,w)->{SharedFeatureStore.save(this,"_chat",cfg.displayName(),"[[qiuqiu-sticker:"+index+"]]","shared");load();}).show();});}new AlertDialog.Builder(this).setTitle("球球动态表情").setView(sc).setNegativeButton("关闭",null).show();}
 GradientDrawable bg(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
 TextView bubble(String s,boolean mine){TextView t=new TextView(this);t.setText(s);t.setTextSize(16);t.setTextColor(0xff4f4141);t.setMaxWidth(dp(280));return t;}
 final Runnable refreshTask=new Runnable(){public void run(){if(cfg.configured())sync.syncAsync((ok,msg)->load());else load();timer.postDelayed(this,5000);}};
 @Override protected void onResume(){super.onResume();if(android.os.Build.VERSION.SDK_INT>=33&&checkSelfPermission(android.Manifest.permission.POST_NOTIFICATIONS)!=android.content.pm.PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{android.Manifest.permission.POST_NOTIFICATIONS},73);RealtimeSyncService.start(this);timer.post(refreshTask);}
 @Override protected void onPause(){timer.removeCallbacks(refreshTask);super.onPause();}
 @Override protected void onDestroy(){io.shutdownNow();super.onDestroy();}
}
