package com.qiuqiu.pet;

import android.app.*;import android.os.*;import android.graphics.Typeface;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;import java.util.concurrent.*;

public class ChatActivity extends Activity {
 final ExecutorService io=Executors.newSingleThreadExecutor();final Handler timer=new Handler(Looper.getMainLooper());ServerConfig cfg;SyncRepository sync;LinearLayout messages;ScrollView scroll;EditText draft;
 int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
 @Override public void onCreate(Bundle b){super.onCreate(b);cfg=new ServerConfig(this);sync=new SyncRepository(this);LinearLayout page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setBackgroundColor(0xfffff8f3);TextView title=new TextView(this);title.setText("💬 我和另一位主人");title.setTextSize(23);title.setTypeface(Typeface.DEFAULT_BOLD);title.setTextColor(0xff594747);title.setGravity(Gravity.CENTER);title.setPadding(0,dp(15),0,dp(10));page.addView(title,new LinearLayout.LayoutParams(-1,-2));scroll=new ScrollView(this);messages=new LinearLayout(this);messages.setOrientation(LinearLayout.VERTICAL);messages.setPadding(dp(12),dp(8),dp(12),dp(8));scroll.addView(messages);page.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));LinearLayout send=new LinearLayout(this);send.setPadding(dp(8),dp(6),dp(8),dp(10));draft=new EditText(this);draft.setHint("说点什么……");draft.setMaxLines(4);send.addView(draft,new LinearLayout.LayoutParams(0,-2,1));Button go=new Button(this);go.setText("发送 💗");go.setOnClickListener(v->send());send.addView(go,new LinearLayout.LayoutParams(dp(100),dp(54)));page.addView(send);setContentView(page);load();}
 void send(){String s=draft.getText().toString().trim();if(s.isEmpty())return;if(!cfg.configured()){Toast.makeText(this,"请先登录账户并创建或加入球球",Toast.LENGTH_LONG).show();return;}SharedFeatureStore.save(this,"_chat",cfg.displayName(),s,"shared");draft.setText("");timer.postDelayed(this::load,250);}
 void load(){io.execute(()->{List<SharedItem> list=SyncDatabase.get(this).shared().byCategory("_chat");Collections.reverse(list);runOnUiThread(()->render(list));});}
 void render(List<SharedItem> list){messages.removeAllViews();if(list.isEmpty()){TextView empty=bubble("还没有消息，先和对方打个招呼吧 🐾",false);messages.addView(empty);}for(SharedItem x:list){boolean mine=x.createdBy.equals(cfg.actorId());LinearLayout row=new LinearLayout(this);row.setGravity(mine?Gravity.END:Gravity.START);LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(14),dp(9),dp(14),dp(9));card.setBackgroundColor(mine?0xffffdfe7:0xffffffff);TextView who=bubble((mine?"我":x.title)+"  "+new SimpleDateFormat("MM-dd HH:mm",Locale.CHINA).format(new Date(x.createdAt)),false);who.setTextSize(11);card.addView(who);card.addView(bubble(x.body,mine));row.addView(card,new LinearLayout.LayoutParams(-2,-2));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(4),0,dp(4));messages.addView(row,lp);}scroll.post(()->scroll.fullScroll(View.FOCUS_DOWN));}
 TextView bubble(String s,boolean mine){TextView t=new TextView(this);t.setText(s);t.setTextSize(16);t.setTextColor(0xff4f4141);t.setMaxWidth(dp(280));return t;}
 final Runnable refreshTask=new Runnable(){public void run(){if(cfg.configured())sync.syncAsync((ok,msg)->load());else load();timer.postDelayed(this,5000);}};
 @Override protected void onResume(){super.onResume();RealtimeSyncService.start(this);timer.post(refreshTask);}
 @Override protected void onPause(){timer.removeCallbacks(refreshTask);super.onPause();}
 @Override protected void onDestroy(){io.shutdownNow();super.onDestroy();}
}
