package com.qiuqiu.pet;

import android.app.*;import android.os.*;import android.graphics.Color;import android.view.*;import android.widget.*;import java.util.*;import java.util.concurrent.*;

public class InsightsActivity extends Activity {
 final ExecutorService io=Executors.newSingleThreadExecutor();LinearLayout body;QiuqiuDatabase db;ServerConfig cfg;
 static final String[] NAMES={"服务器连接灯","待同步云朵徽标","双人头像在线环","共享活动时间线","今日贡献双环图","球球五维状态盘","情绪趋势折线","睡眠与活动带","共同任务进度轨","连续陪伴日历","成长树","性格雷达图","关系温度卡","房间布置版本轴","衣柜搭配预览","食物与反应图鉴","旅行地图与明信片","成就墙","纪念日时间轴","共享照片墙","记忆星图","同步差异预览","冲突与补偿记录","设备与权限图","隐私范围标签","服务器存储仪表盘","月度回顾故事页","事件回放模式"};
 static final String[] SOURCE={"","","","双人实时动作回声","贡献回顾","","每日心情签到","双人哄睡仪式","共同照顾任务","贡献回顾","成长树","性格养成","每日心情签到","房间共同装修","衣柜搭配投票","发现图鉴","旅行明信片","成就墙","纪念日时间轴","共享日记","共享 AI 记忆","","","","","","月度共同回顾","双人实时动作回声"};
 int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
 @Override public void onCreate(Bundle s){super.onCreate(s);db=QiuqiuDatabase.get(this);cfg=new ServerConfig(this);ScrollView scroll=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(18),dp(20),dp(18),dp(30));body.setBackgroundColor(0xfff8f5f2);scroll.addView(body);setContentView(scroll);load();}
 void load(){io.execute(()->{int pending=db.sync().pendingCount();List<SyncOperation> timeline=db.sync().timeline(100);List<SharedItem> items=db.shared().all();runOnUiThread(()->render(pending,timeline,items));});}
 TextView text(String s,int size){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(0xff443f39);t.setPadding(0,dp(5),0,dp(5));body.addView(t);return t;}
 void render(int pending,List<SyncOperation> timeline,List<SharedItem> items){body.removeAllViews();text("成长与同步数据",28);text((cfg.configured()?"● 已绑定服务器":"○ 尚未绑定服务器")+"  ·  待同步 "+pending+" 条",14);Map<String,Integer> count=new HashMap<>();for(SharedItem x:items)count.put(x.category,count.getOrDefault(x.category,0)+1);for(int i=0;i<NAMES.length;i++){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(12),dp(8),dp(12),dp(8));card.setBackgroundColor(Color.WHITE);card.setContentDescription(NAMES[i]+"。"+detail(i,pending,timeline,items,count));TextView title=new TextView(this);title.setText((i+1)+"  "+NAMES[i]);title.setTextSize(17);title.setTextColor(0xff443f39);card.addView(title);ProgressBar bar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);bar.setMax(100);bar.setProgress(progress(i,pending,timeline,items,count));card.addView(bar,new LinearLayout.LayoutParams(-1,dp(12)));TextView detail=new TextView(this);detail.setText(detail(i,pending,timeline,items,count));detail.setTextSize(12);detail.setTextColor(0xff766a63);detail.setPadding(0,dp(5),0,0);card.addView(detail);final int index=i;card.setOnClickListener(v->open(index));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(5),0,dp(5));body.addView(card,lp);}}
 int progress(int i,int pending,List<SyncOperation> timeline,List<SharedItem> items,Map<String,Integer> count){if(i==0)return cfg.configured()?100:0;if(i==1)return pending==0?100:Math.max(5,100-Math.min(95,pending*5));if(i==3||i==4||i==27)return Math.min(100,timeline.size()*5);if(i==5)return new Companion(this).affection;String source=SOURCE[i];return source.isEmpty()?Math.min(100,items.size()*4):Math.min(100,count.getOrDefault(source,0)*20);}
 void open(int i){if(i==0||i==1)startActivity(new android.content.Intent(this,ServerSetupActivity.class));else if(i==21||i==22||i==23||i==25)startActivity(new android.content.Intent(this,SyncAdminActivity.class));else if(!SOURCE[i].isEmpty()){FeatureCatalog.Def d=FeatureCatalog.get(SOURCE[i]);Class<?> target=d.name.equals("异步双人小游戏")?MiniGameActivity.class:VisualFeatureActivity.class;startActivity(new android.content.Intent(this,target).putExtra("category",d.name).putExtra("description",d.description));}}
 String detail(int i,int pending,List<SyncOperation> timeline,List<SharedItem> items,Map<String,Integer> count){switch(i){case 0:return cfg.configured()?"在线配置已保存；最后同步："+(cfg.lastSync()==0?"从未":new Date(cfg.lastSync())):"未绑定服务器，点击连接";case 1:return pending==0?"✓ 队列为空，全部操作已同步":"☁ "+pending+" 条待同步；离线内容不会丢失";case 2:return cfg.configured()?"设备身份已绑定；点击查看双方设备":"尚未绑定设备";case 3:return "按服务端顺序保留最近 "+timeline.size()+" 条事件";case 4:return "共 "+timeline.size()+" 次可追溯照顾，不比较输赢";case 5:Companion c=new Companion(this);PetState p=new PetState(this);return "亲密 "+c.affection+"/100 · 清洁待办 "+(p.poop+p.urine)+" · 心情 "+c.mood(System.currentTimeMillis());case 21:return "存在人工冲突时显示本机值、共享值与推荐结果";case 22:return "点击查看服务端冲突、补偿与原因";case 23:return "点击查看主人、设备、最后上线和撤销状态";case 24:return "👤个人 · 👥共享 · 🔒敏感，状态不只靠颜色表达";case 25:return "点击查看服务器、设备和同步诊断";default:String source=SOURCE[i];int n=source.isEmpty()?items.size():count.getOrDefault(source,0);return n==0?"暂无数据；点击进入后可离线创建":"已有 "+n+" 条真实记录；点击查看";}}
 @Override protected void onDestroy(){io.shutdownNow();super.onDestroy();}
}
