package com.qiuqiu.pet;

import android.Manifest;import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.net.Uri;import android.provider.MediaStore;import android.view.*;import android.widget.*;import java.io.*;import java.text.*;import java.util.*;import java.util.concurrent.*;

public class PhotoViewerActivity extends Activity {
 final ExecutorService io=Executors.newSingleThreadExecutor();byte[] photo;ImageView image;Button save;
 int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.BLACK);FrameLayout page=new FrameLayout(this);page.setBackgroundColor(Color.BLACK);image=new ImageView(this);image.setScaleType(ImageView.ScaleType.FIT_CENTER);page.addView(image,new FrameLayout.LayoutParams(-1,-1));image.setOnClickListener(v->toggleControls());Button close=new Button(this);close.setText("‹ 返回");close.setTextColor(Color.WHITE);close.setBackgroundColor(0x66000000);close.setOnClickListener(v->finish());FrameLayout.LayoutParams clp=new FrameLayout.LayoutParams(dp(90),dp(48),Gravity.TOP|Gravity.LEFT);clp.setMargins(dp(10),dp(12),0,0);page.addView(close,clp);save=new Button(this);save.setText("保存到手机相册");save.setEnabled(false);save.setOnClickListener(v->requestSave());FrameLayout.LayoutParams slp=new FrameLayout.LayoutParams(dp(170),dp(52),Gravity.BOTTOM|Gravity.CENTER_HORIZONTAL);slp.setMargins(0,0,0,dp(22));page.addView(save,slp);setContentView(page);controls=new View[]{close,save};String id=getIntent().getStringExtra("itemId");io.execute(()->{SharedItem item=SyncDatabase.get(this).shared().byId(id);photo=item==null?null:AlbumImages.bytes(item.body);Bitmap bitmap=photo==null?null:BitmapFactory.decodeByteArray(photo,0,photo.length);runOnUiThread(()->{if(bitmap==null){Toast.makeText(this,"照片读取失败",Toast.LENGTH_LONG).show();finish();}else{image.setImageBitmap(bitmap);save.setEnabled(true);}});});}
 View[] controls;
 void toggleControls(){if(controls==null)return;boolean show=controls[0].getVisibility()!=View.VISIBLE;for(View v:controls)v.setVisibility(show?View.VISIBLE:View.GONE);}
 void requestSave(){if(Build.VERSION.SDK_INT<29&&checkSelfPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE},91);return;}savePhoto();}
 @Override public void onRequestPermissionsResult(int request,String[] permissions,int[] results){super.onRequestPermissionsResult(request,permissions,results);if(request==91&&results.length>0&&results[0]==PackageManager.PERMISSION_GRANTED)savePhoto();else Toast.makeText(this,"需要存储权限才能保存照片",Toast.LENGTH_LONG).show();}
 void savePhoto(){if(photo==null)return;save.setEnabled(false);io.execute(()->{Uri uri=null;try{ContentValues values=new ContentValues();values.put(MediaStore.Images.Media.DISPLAY_NAME,"球球相册_"+new SimpleDateFormat("yyyyMMdd_HHmmss",Locale.CHINA).format(new Date())+".jpg");values.put(MediaStore.Images.Media.MIME_TYPE,"image/jpeg");if(Build.VERSION.SDK_INT>=29){values.put(MediaStore.Images.Media.RELATIVE_PATH,Environment.DIRECTORY_PICTURES+"/球球相册");values.put(MediaStore.Images.Media.IS_PENDING,1);}uri=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,values);if(uri==null)throw new IOException("无法创建照片");try(OutputStream out=getContentResolver().openOutputStream(uri)){out.write(photo);}if(Build.VERSION.SDK_INT>=29){ContentValues done=new ContentValues();done.put(MediaStore.Images.Media.IS_PENDING,0);getContentResolver().update(uri,done,null,null);}runOnUiThread(()->{Toast.makeText(this,"已保存到手机相册/Pictures/球球相册",Toast.LENGTH_LONG).show();save.setEnabled(true);});}catch(Exception e){if(uri!=null)getContentResolver().delete(uri,null,null);runOnUiThread(()->{Toast.makeText(this,"保存失败："+e.getMessage(),Toast.LENGTH_LONG).show();save.setEnabled(true);});}});}
 @Override protected void onDestroy(){io.shutdownNow();super.onDestroy();}
}
