package com.qiuqiu.pet;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.net.Uri;import android.provider.MediaStore;import android.util.Base64;import android.view.*;import android.widget.*;import java.io.*;import java.text.*;import java.util.*;import java.util.concurrent.*;

public class VisualFeatureActivity extends Activity {
 static final int PICK_IMAGE=48; static final String IMAGE_MARK="[[qiuqiu-image:xx"; final ExecutorService io=Executors.newSingleThreadExecutor(); final Handler ui=new Handler(Looper.getMainLooper());
 String category,choice="",extraChoice="",scope="shared",imageData="",chosenDate="";FeatureCatalog.Def def;LinearLayout list,choiceBox;ImageView preview;TextView chosen;EditText note;SeekBar energy;
 int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
 GradientDrawable bg(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));d.setStroke(dp(1),0x22a95870);return d;}
 TextView label(LinearLayout p,String s,int z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(0xff5a4545);t.setPadding(dp(4),dp(7),dp(4),dp(7));p.addView(t);return t;}
 @Override public void onCreate(Bundle b){super.onCreate(b);category=getIntent().getStringExtra("category");def=FeatureCatalog.get(category);ScrollView scroll=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(20),dp(18),dp(30));root.setBackgroundColor(0xfffff8f3);scroll.addView(root);
  TextView hero=label(root,icon(category)+"  "+category,28);hero.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);label(root,def.description,14);chosen=label(root,"请选择下方图形选项",13);
  choiceBox=new LinearLayout(this);choiceBox.setOrientation(LinearLayout.VERTICAL);root.addView(choiceBox);buildChoices();
  if(category.equals("每日心情签到")){label(root,"今天的能量",16);energy=new SeekBar(this);energy.setMax(4);energy.setProgress(2);energy.setContentDescription("能量等级，一到五");root.addView(energy);}
  if(def.supportsDate){Button date=new Button(this);date.setText("📅  选择日期或解锁日");date.setOnClickListener(v->pickDate(date));root.addView(date,new LinearLayout.LayoutParams(-1,dp(52)));}
  if(photoFeature()){Button photo=new Button(this);photo.setText("📷  从相册选择照片");photo.setOnClickListener(v->startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE),PICK_IMAGE));root.addView(photo,new LinearLayout.LayoutParams(-1,dp(52)));preview=new ImageView(this);preview.setAdjustViewBounds(true);preview.setScaleType(ImageView.ScaleType.CENTER_CROP);preview.setVisibility(View.GONE);root.addView(preview,new LinearLayout.LayoutParams(-1,dp(210)));}
  label(root,"分享范围",16);LinearLayout privacy=new LinearLayout(this);root.addView(privacy);privacy.addView(scopeButton("👥 双方", "shared"),new LinearLayout.LayoutParams(0,dp(48),1));privacy.addView(scopeButton("👤 自己", "personal"),new LinearLayout.LayoutParams(0,dp(48),1));privacy.addView(scopeButton("🔒 敏感", "sensitive"),new LinearLayout.LayoutParams(0,dp(48),1));
  note=new EditText(this);note.setHint("可选备注（不是必填项）");note.setMinLines(2);root.addView(note,new LinearLayout.LayoutParams(-1,-2));Button save=new Button(this);save.setText("💗  保存这次互动");save.setOnClickListener(v->save());root.addView(save,new LinearLayout.LayoutParams(-1,dp(56)));
  label(root,"最近记录",20);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list);setContentView(scroll);load();
 }
 Button scopeButton(String text,String value){Button b=new Button(this);b.setText(text);b.setOnClickListener(v->{scope=value;Toast.makeText(this,"已选择："+text,Toast.LENGTH_SHORT).show();});return b;}
 void buildChoices(){String[][] rows=options(category);for(String[] row:rows){LinearLayout line=new LinearLayout(this);line.setGravity(Gravity.CENTER);choiceBox.addView(line);for(String value:row){Button b=new Button(this);b.setText(value);b.setTextSize(17);b.setOnClickListener(v->{choice=value;chosen.setText("已选择："+value);highlight(b,line);});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(62),1);lp.setMargins(dp(3),dp(3),dp(3),dp(3));line.addView(b,lp);}}}
 void highlight(Button selected,LinearLayout row){for(int i=0;i<row.getChildCount();i++)row.getChildAt(i).setAlpha(row.getChildAt(i)==selected?1f:.55f);}
 String[][] options(String c){
  if(c.equals("每日心情签到"))return new String[][]{{"😊 开心","😌 平静","🥺 难过"},{"😴 疲惫","😤 烦躁","🤩 兴奋"},{"🤗 想抱抱","☕ 陪我聊聊","🌙 安静陪伴"}};
  if(c.equals("共同照顾任务")||c.equals("照顾接力单"))return new String[][]{{"🍚 喂食","🧹 清洁","🪮 梳毛"},{"🎾 陪玩","🌙 哄睡","🎀 装扮"}};
  if(c.equals("房间共同装修"))return new String[][]{{"🌸 樱花房","🌙 星空房","🌿 森林房"},{"🛋️ 沙发","🪴 绿植","🧸 玩偶"}};
  if(c.equals("衣柜搭配投票"))return new String[][]{{"🎀 甜美","🧢 活力","🧣 温暖"},{"👑 华丽","🌿 清新","🌙 睡衣"}};
  if(c.equals("成长树"))return new String[][]{{"💗 陪伴枝","🍚 照顾枝"},{"🧭 探索枝","💞 默契枝"}};
  if(c.equals("性格养成"))return new String[][]{{"🐾 黏人","🌙 安静","✨ 好奇"},{"🍽️ 小吃货","🎾 爱玩","🛋️ 慵懒"}};
  if(c.equals("旅行明信片")||c.equals("离线旅行包"))return new String[][]{{"🏖️ 海边","🏔️ 山野","🏙️ 城市"},{"🌸 花园","🚂 小镇","🌌 星空"}};
  if(c.equals("发现图鉴"))return new String[][]{{"🍣 食物反应","🧸 家具互动"},{"🐾 新动作","🎵 新叫声"}};
  if(c.equals("成就墙"))return new String[][]{{"🏅 共同照顾","💞 默契时刻"},{"📸 回忆收藏","🌟 连续陪伴"}};
  if(c.equals("远程抱抱"))return new String[][]{{"🤗 大抱抱","💋 亲亲","👉 轻轻戳"},{"💗 想你啦","🐾 球球代送","🌙 晚安抱"}};
  if(c.equals("和好模式"))return new String[][]{{"🫧 冷静 10 分钟","🌿 冷静 30 分钟"},{"💌 写一句好话","🤝 一起完成小任务"}};
  if(c.equals("约会愿望单"))return new String[][]{{"🍜 一起吃饭","🎬 看电影","🌳 去散步"},{"🎨 做手工","🚗 小旅行","🏠 宅家约会"}};
  if(c.equals("双人哄睡仪式"))return new String[][]{{"🌙 晚安","🫶 今天辛苦了","✨ 做个好梦"},{"🐈 球球守夜","🎵 睡前音乐","💗 明天见"}};
  if(c.equals("季节通行日历"))return new String[][]{{"🌸 春日","☀️ 夏日","🍂 秋日","❄️ 冬日"}};
  if(c.equals("每日情侣问题")||c.equals("默契猜猜看"))return new String[][]{{"💗 很喜欢","🙂 还不错"},{"🤔 不确定","🌿 想慢慢聊"}};
  if(c.equals("关系暂停与告别"))return new String[][]{{"⏸️ 暂停同步","📦 导出回忆"},{"🔐 撤销设备","🌱 恢复关系"}};
  return new String[][]{{"💗 温馨时刻","🐈 球球日常","✨ 特别发现"},{"📌 共同计划","🎁 惊喜","🌙 安静陪伴"}};
 }
 String icon(String c){if(c.contains("照片")||c.contains("日记")||c.contains("回顾"))return "📷";if(c.contains("旅行"))return "🗺️";if(c.contains("成长")||c.contains("性格"))return "🌳";if(c.contains("任务")||c.contains("接力"))return "✅";if(c.contains("抱抱")||c.contains("心情")||c.contains("情侣"))return "💗";return "🐾";}
 boolean photoFeature(){return category.contains("日记")||category.contains("照片")||category.contains("纪念")||category.contains("明信片")||category.contains("回顾")||category.contains("时光胶囊")||category.contains("导出册");}
 void pickDate(Button button){Calendar c=Calendar.getInstance();new DatePickerDialog(this,(v,y,m,d)->{chosenDate=String.format(Locale.CHINA,"%04d-%02d-%02d",y,m+1,d);button.setText("📅  "+chosenDate);},c.get(Calendar.YEAR),c.get(Calendar.MONTH),c.get(Calendar.DAY_OF_MONTH)).show();}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==PICK_IMAGE&&result==RESULT_OK&&data!=null){io.execute(()->{try{Bitmap src=MediaStore.Images.Media.getBitmap(getContentResolver(),data.getData());int max=Math.max(src.getWidth(),src.getHeight());float scale=max>900?900f/max:1f;Bitmap out=scale<1?Bitmap.createScaledBitmap(src,Math.round(src.getWidth()*scale),Math.round(src.getHeight()*scale),true):src;ByteArrayOutputStream bytes=new ByteArrayOutputStream();out.compress(Bitmap.CompressFormat.JPEG,68,bytes);imageData=Base64.encodeToString(bytes.toByteArray(),Base64.NO_WRAP);runOnUiThread(()->{preview.setImageBitmap(out);preview.setVisibility(View.VISIBLE);});}catch(Exception e){runOnUiThread(()->Toast.makeText(this,"照片读取失败",Toast.LENGTH_LONG).show());}});}}
 void save(){if(choice.isEmpty()){Toast.makeText(this,"请先点选一个图形选项",Toast.LENGTH_SHORT).show();return;}if(scope.equals("sensitive"))scope="personal";String body="选择："+choice+(energy==null?"":"\n能量："+(energy.getProgress()+1)+"/5")+(chosenDate.isEmpty()?"":"\n日期："+chosenDate)+(note.getText().toString().trim().isEmpty()?"":"\n备注："+note.getText().toString().trim());if(!imageData.isEmpty())body+="\n"+IMAGE_MARK+imageData+"]]";SharedFeatureStore.save(this,category,choice,body,scope);choice="";imageData="";note.setText("");if(preview!=null)preview.setVisibility(View.GONE);chosen.setText("已保存 💗 可以继续选择");load();}
 void load(){ui.postDelayed(()->io.execute(()->{List<SharedItem> items=SyncDatabase.get(this).shared().byCategory(category);runOnUiThread(()->render(items));}),180);}
 void render(List<SharedItem> items){list.removeAllViews();if(items.isEmpty()){label(list,"还没有记录，点选上方图案就可以开始。",14);return;}for(SharedItem item:items){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(14),dp(10),dp(14),dp(10));card.setBackground(bg(0xffffffff,20));String clean=item.body;int a=clean.indexOf("[[qiuqiu-image:");if(a>=0){int e=clean.indexOf("]]",a);if(e>a){String data=clean.substring(a+17,e);clean=(clean.substring(0,a)+clean.substring(e+2)).trim();try{byte[] bytes=Base64.decode(data,Base64.DEFAULT);ImageView image=new ImageView(this);image.setImageBitmap(BitmapFactory.decodeByteArray(bytes,0,bytes.length));image.setScaleType(ImageView.ScaleType.CENTER_CROP);image.setAdjustViewBounds(true);card.addView(image,new LinearLayout.LayoutParams(-1,dp(190)));}catch(Exception ignored){}}}label(card,item.title,19);label(card,clean,14);label(card,(item.privacyScope.equals("shared")?"👥 双方共享":"👤 仅自己")+"  ·  "+new SimpleDateFormat("MM-dd HH:mm",Locale.CHINA).format(new Date(item.updatedAt)),12);LinearLayout actions=new LinearLayout(this);card.addView(actions);Button done=new Button(this);done.setText(item.status.equals("completed")?"↩ 重新打开":"✓ 完成");done.setOnClickListener(v->{item.status=item.status.equals("completed")?"active":"completed";SharedFeatureStore.update(this,item,false);load();});actions.addView(done,new LinearLayout.LayoutParams(0,dp(46),1));Button del=new Button(this);del.setText("🗑 删除");del.setOnClickListener(v->new AlertDialog.Builder(this).setMessage("删除这条记录？").setNegativeButton("取消",null).setPositiveButton("删除",(d,w)->{SharedFeatureStore.update(this,item,true);load();}).show());actions.addView(del,new LinearLayout.LayoutParams(0,dp(46),1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(7),0,dp(7));list.addView(card,lp);}}
 @Override protected void onDestroy(){ui.removeCallbacksAndMessages(null);io.shutdownNow();super.onDestroy();}
}
